### ISSUE TITLE
No Config Menu.

### ISSUE THREAD

**Issue by Big-ed69** [Abstrusle/MouserateFramerate#1]
Hello, Just discovered this mod on fabricord and installed it. I have cloth config installed along with mod menu.

However I cannot find a config menu for this mod. The mod loads and is in mod menu but no option for a gui or config menu is present.
The mod works fine in game however not being able to configure the mod is irritating.

**Comment by HyperSoop** [comment]
If you can't find an in-game menu, you might want to look at the config folder.

**Comment by HyperSoop** [comment]
> I am aware of the config file, however cloth config api is listed as a dependency and afaik clotth config api is for use with a gui config menu.

then either the mod is broken or the author is dumb
